# Generated by Django 2.2.16 on 2022-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220808_1033'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_favorites',
        ),
    ]
