# Generated by Django 2.2.16 on 2022-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220812_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredsAmount',
            new_name='IngredientsAmount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='api.IngredientsAmount', to='api.Ingredient', verbose_name='Recipe Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='api.Tag', verbose_name='Recipe Tag'),
        ),
    ]
