# Generated by Django 2.2.16 on 2022-08-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220805_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredsamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreds_list', to='api.Recipe', verbose_name='Recipe ingreds list'),
        ),
    ]
