# Generated by Django 2.2.16 on 2022-08-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220805_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredsamount',
            old_name='ingedient',
            new_name='ingredient',
        ),
    ]
