# Generated by Django 2.2.16 on 2022-08-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
    ]
